//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalApplicationWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAProduct
    {
        public int IAProdict_ID { get; set; }
        public int IA_ID { get; set; }
        public int Product_ID { get; set; }
        public int IAP_Amount { get; set; }
    
        public virtual InternalApplication InternalApplication { get; set; }
        public virtual Product Product { get; set; }
    }
}
