//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalApplicationWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptIngridients
    {
        public int RI_ID { get; set; }
        public int Product_ID { get; set; }
        public int Ingridient_ID { get; set; }
        public decimal RI_Amount { get; set; }
    
        public virtual Ingridient Ingridient { get; set; }
        public virtual Product Product { get; set; }
    }
}
