//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalApplicationWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Status()
        {
            this.InternalApplication = new HashSet<InternalApplication>();
        }
    
        public int Status_ID { get; set; }
        public string Status_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalApplication> InternalApplication { get; set; }
    }

    public partial class Status
    {
        public string Color
        {
            get
            {
                if (Status_ID == 1)
                {
                    return "Yellow";
                }
                else if (Status_ID == 2)
                {
                    return "Green";
                }
                else
                {
                    return "Red";
                }

            }
        }
    }
}

