//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalApplicationWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierIngridient
    {
        public int SI_ID { get; set; }
        public int Supplier_ID { get; set; }
        public int Ingridient_ID { get; set; }
    
        public virtual Ingridient Ingridient { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
